- django_graph_api/graphql/tests/test_graphql.py
- setup.cfg
Move tests.py to tests/test_graphql.py such that pytest can collect it. Add setup.cfg to use pytest when running setuptools test.
> pytest restructuring

- .travis.yaml
- requirements.txt
Resolved #4. Added continuous integration support.
> 4 continuous integration

- README.rst
This PR adds contribution guidelines (including COC and style guide) to the README.
> Contribution guidelines

- .gitignore
- django_graph_api/graphql/types.py
- django_graph_api/tests/graphql/test_types.py
- django_graph_api/tests/starwars/models.py
- django_graph_api/tests/starwars/schema.py
- django_graph_api/tests/starwars/tests/conftest.py
- django_graph_api/tests/starwars/tests/test_basic.py
- requirements-test.txt
> Add comprehensive tests for scalar result coercion

- django_graph_api/graphql/types.py
- django_graph_api/tests/graphql/test_types.py
- django_graph_api/views.py
> Add tests for coercing list results

- README.rst
Added travis badge to README and moved badges to be inline with the project title.
> Added travis badge to README

- CHANGES.txt
- MANIFEST.in
- setup.py
This is mostly based off of Kenneth Reitz's [setup.py](https://github.com/kennethreitz/setup.py/blob/master/setup.py) and [Hitchhiker's guide to packaging](https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html).
To upload to PyPi:
```
$ pip install twine
$ python setup.py upload
```
> Get it ready for pypi

- README.rst
- docs/define_schema.rst
- docs/index.rst
Tweaked readme to match docs more, added links to documentation, and added section on custom field value logic.
> Docs improvements

- django_graph_api/graphql/types.py
- django_graph_api/tests/graphql/test_types.py
- django_graph_api/tests/test_basic.py
- test_app/schema.py
> Make RelatedField support `self` reference

- django_graph_api/graphql/helpers.py
- django_graph_api/graphql/types.py
- django_graph_api/tests/test_basic.py
- docs/conf.py
- docs/define_schema.rst
- test_app/models.py
- test_app/schema.py
> Allow for circular class references in related fields using lambdas

- django_graph_api/graphql/schema.py
- django_graph_api/graphql/types.py
- django_graph_api/graphql/utils.py
- django_graph_api/tests/test_fragments.py
- django_graph_api/tests/test_introspection.py
- test_app/schema.py
Resolved #47 - added support for fragments, inline and otherwise.
> 47 fragments

- django_graph_api/graphql/schema.py
- django_graph_api/graphql/types.py
- django_graph_api/tests/conftest.py
- django_graph_api/tests/graphql/test_types.py
- django_graph_api/tests/test_arguments.py
- django_graph_api/tests/test_basic.py
- django_graph_api/tests/test_introspection.py
- django_graph_api/tests/test_views.py
- test_app/schema.py
> 32 Support arguments

- django_graph_api/graphql/schema.py
- django_graph_api/graphql/types.py
- django_graph_api/tests/test_introspection.py
Improves support for introspection.
> Introspection improvements

- django_graph_api/tests/conftest.py
- docs/start_developing.rst
- test_app/management/commands/create_test_data.py
> Add create_test_data management command

- .travis.yml
Create an environment variable to contain django versions and
update the pip install command to install the version of django
specified in the env var
> Add django ver as env var to .travis.yml

- django_graph_api/views.py
- docs/start_developing.rst
Fix #74 
<strike>Also ninja a doc update in to load all the conftest data </strike>
> bump graphiql version 0.11.11

- django_graph_api/tests/test_views.py
- django_graph_api/views.py
> Django 1.8 compatibility fixes

- django_graph_api/graphql/types.py
- django_graph_api/tests/test_introspection.py
- docs/define_schema.rst
- test_app/schema.py
> Support string import with full class path

- .travis.yml
So that we can get notifications as requested in #96.
> Added travis notifications for slack

- django_graph_api/graphql/schema.py
- django_graph_api/graphql/types.py
- django_graph_api/tests/test_introspection.py
- test_app/schema.py
> Implement non-null args

- django_graph_api/graphql/request.py
- django_graph_api/tests/test_views.py
- django_graph_api/tests/validation/test_basic.py
Resolved #63. Added special case for the error of having a blank query.
> Made special-case error for blank documents

- Pipfile
- Pipfile.lock
- django_graph_api/graphql/ast_helpers.py
- django_graph_api/graphql/request.py
- django_graph_api/graphql/schema.py
- django_graph_api/graphql/types.py
- django_graph_api/graphql/utils.py
- django_graph_api/graphql/validation.py
- django_graph_api/tests/graphql/test_types.py
- django_graph_api/tests/test_arguments.py
- django_graph_api/tests/test_basic.py
- django_graph_api/tests/test_errors.py
- django_graph_api/tests/test_fragments.py
- django_graph_api/tests/test_introspection.py
- django_graph_api/tests/test_variables.py
- django_graph_api/tests/test_views.py
- django_graph_api/tests/validation/test_arguments.py
- django_graph_api/tests/validation/test_basic.py
- django_graph_api/tests/validation/test_operations.py
- django_graph_api/views.py
- test_app/schema.py
> 102 non null arg validation
